language: python
sudo: false
python:
- '3.4'
addons:
  postgresql: "9.3"

cache:
  directories:
  - $HOME/.pip-cache/

install:
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  # - pip install coveralls

env:
  - DJANGO_SETTINGS_MODULE="settings.test_settings" SECRET_KEY=test

script:
- flake8
- python manage.py test
# - coverage run --source=junction --omit='*tests*,*commands*,*migrations*,*admin*,*wsgi*' -m -v --tb=native
# - coverage report -m

# after_success:
#   coveralls
